substitutions:
  _REGION: asia-east1
  _REPOSITORY: escape-nthu
  _IMAGE: server

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - server/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest
      - .
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest
